// Copyright 2022 Shattered Realms Online

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/PlayerController.h"
#include "SROPlayerController.generated.h"

/**
 * 
 */
UCLASS()
class SRO_API ASROPlayerController : public APlayerController
{
	GENERATED_BODY()
public:
	virtual void BeginPlay() override;

	/** The authentication token for the player generated by the SRO authentication service */
	UPROPERTY(BlueprintReadWrite, Category = "Authentication")
	FString AuthToken;
};
