//Generated by TurboLink CodeGenerator, do not edit!
#include "CharactersService_Private.h"

void UCharactersServiceGetGendersLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharactersGenders& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(GrpcResult, Response);
	InnerClient->OnGetGendersResponse.RemoveDynamic(this, &UCharactersServiceGetGendersLambdaWrapper::OnResponse);
}

void UCharactersServiceGetRealmsLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharactersRealms& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(GrpcResult, Response);
	InnerClient->OnGetRealmsResponse.RemoveDynamic(this, &UCharactersServiceGetRealmsLambdaWrapper::OnResponse);
}

void UCharactersServiceGetCharactersLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharactersCharactersResponse& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(GrpcResult, Response);
	InnerClient->OnGetCharactersResponse.RemoveDynamic(this, &UCharactersServiceGetCharactersLambdaWrapper::OnResponse);
}

void UCharactersServiceGetCharacterLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharactersCharacterResponse& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(GrpcResult, Response);
	InnerClient->OnGetCharacterResponse.RemoveDynamic(this, &UCharactersServiceGetCharacterLambdaWrapper::OnResponse);
}

void UCharactersServiceCreateCharacterLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharactersCharacterResponse& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(GrpcResult, Response);
	InnerClient->OnCreateCharacterResponse.RemoveDynamic(this, &UCharactersServiceCreateCharacterLambdaWrapper::OnResponse);
}

void UCharactersServiceDeleteCharacterLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(GrpcResult, Response);
	InnerClient->OnDeleteCharacterResponse.RemoveDynamic(this, &UCharactersServiceDeleteCharacterLambdaWrapper::OnResponse);
}

void UCharactersServiceGetAllCharactersForUserLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharactersCharactersResponse& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(GrpcResult, Response);
	InnerClient->OnGetAllCharactersForUserResponse.RemoveDynamic(this, &UCharactersServiceGetAllCharactersForUserLambdaWrapper::OnResponse);
}

void UCharactersServiceEditCharacterLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(GrpcResult, Response);
	InnerClient->OnEditCharacterResponse.RemoveDynamic(this, &UCharactersServiceEditCharacterLambdaWrapper::OnResponse);
}

void UCharactersServiceAddCharacterPlayTimeLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroCharactersPlayTimeResponse& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(GrpcResult, Response);
	InnerClient->OnAddCharacterPlayTimeResponse.RemoveDynamic(this, &UCharactersServiceAddCharacterPlayTimeLambdaWrapper::OnResponse);
}

