// Copyright Shattered Realms Online All Rights Reserved

#pragma once

#include "CoreMinimal.h"
#include "SROOfflineController.generated.h"


UCLASS()
class SRO_API ASROOfflineController : public APlayerController
{
	GENERATED_BODY()

protected:
	// Called when the game starts
	virtual void BeginPlay() override;

public:

	/** The authentication token for the player generated by the SRO authentication service */
	UPROPERTY(BlueprintReadWrite, Category = "Authentication")
	FString AuthToken;

	UPROPERTY(BlueprintReadWrite, Category = "Authentication")
	int32 UserId;

	UFUNCTION(BlueprintCallable)
	void Logout();
};
