//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcContext.h"
#include "SSro/HealthMessage.h"
#include "SSro/HealthMarshaling.h"
class GrpcContext_HealthService_Health : public GrpcContext_Ping_Pong<HealthService_Health_ReaderWriter, ::sro::HealthMessage>
{
	friend class UHealthServiceClient;
	typedef GrpcContext_Ping_Pong<HealthService_Health_ReaderWriter, ::sro::HealthMessage> Super;

private:
	void Call(const FGrpcGoogleProtobufEmpty& Request);
	virtual void OnRpcEvent(bool Ok, const void* EventTag) override;

public:
	GrpcContext_HealthService_Health(FGrpcContextHandle _Handle, UGrpcService* _Service, UGrpcClient* _Client);
};

