//Generated by TurboLink CodeGenerator, do not edit!
#include "SSro/HealthClient.h"
#include "SSro/HealthService.h"
#include "HealthContext.h"
#include "TurboLinkGrpcManager_Private.h"
#include "Templates/SharedPointer.h"

FGrpcContextHandle UHealthServiceClient::InitHealth()
{
	FGrpcContextHandle handle = Service->TurboLinkManager->GetNextContextHandle();
	auto context = UGrpcClient::MakeContext<GrpcContext_HealthService_Health>(handle);
	context->RpcContext = UTurboLinkGrpcManager::Private::CreateRpcClientContext();
	return context->GetHandle();
}

void UHealthServiceClient::Health(FGrpcContextHandle Handle, const FGrpcGoogleProtobufEmpty& Request)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		auto contextHealth = StaticCastSharedPtr<GrpcContext_HealthService_Health>(*context);
		contextHealth->Call(Request);
	}
}
void UHealthServiceClient::TryCancel(FGrpcContextHandle Handle)
{
	auto context = UGrpcClient::GetContext(Handle);
	if (context != nullptr)
	{
		(*context)->TryCancel();
	}
}

void UHealthServiceClient::Shutdown()
{
	OnHealthResponse.Clear();
	Super::Shutdown();
}
