//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "SGoogleApi/AnnotationsMessage.h"
#include "SGoogleProtobuf/EmptyMessage.h"
#include "HealthMessage.generated.h"

USTRUCT(BlueprintType, meta = (DisplayName="Sro.HealthMessage"))
struct FGrpcSroHealthMessage : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite)
    FString Status = "";
};
