//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcMessage.h"
#include "GlobalsMessage.generated.h"

UENUM(BlueprintType, meta = (DisplayName="Sro.UserTarget.Target"))
enum class EGrpcSroUserTargetTarget : uint8
{
    Id=0,
    Username=1,
};

USTRUCT(BlueprintType, meta = (DisplayName="Sro.UserTarget.Target",
    HasNativeMake = "TurboLinkGrpc.GrpcSroUserTargetTargetHelperLibrary.MakeTarget",
    HasNativeBreak = "TurboLinkGrpc.GrpcSroUserTargetTargetHelperLibrary.BreakTarget"))
struct FGrpcSroUserTargetTarget : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite)
    EGrpcSroUserTargetTarget TargetCase;

    UPROPERTY(BlueprintReadWrite)
    FString Id = "";

    UPROPERTY(BlueprintReadWrite)
    FString Username = "";
};

USTRUCT(BlueprintType, meta = (DisplayName="Sro.UserTarget"))
struct FGrpcSroUserTarget : public FGrpcMessage
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite)
    FGrpcSroUserTargetTarget Target;
};

UCLASS()
class UGrpcSroUserTargetTargetHelperLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()
public:
    UFUNCTION(BlueprintPure, Category = "TurboLink|Sro", meta=(BlueprintThreadSafe))
    static FGrpcSroUserTargetTarget MakeTarget(EGrpcSroUserTargetTarget TargetCase, 
        FString Id, FString Username 
    );

    UFUNCTION(BlueprintPure, Category = "TurboLink|Sro", meta=(BlueprintThreadSafe))
    static void BreakTarget(const FGrpcSroUserTargetTarget& Target, EGrpcSroUserTargetTarget& TargetCase, 
        FString& Id, FString& Username 
    );
};
