//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SSro/HealthMessage.h"
#include "HealthClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnHealthServiceHealthResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroHealthMessage&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UHealthServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnHealthServiceHealthResponse OnHealthResponse;

public:
	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitHealth();

	UFUNCTION(BlueprintCallable)
	void Health(FGrpcContextHandle Handle, const FGrpcGoogleProtobufEmpty& Request);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable)
	void TryCancel(FGrpcContextHandle Handle);
};

