// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: connection.proto

#include "connection.pb.h"
#include "connection.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace sro {
namespace gamebackend {

static const char* ConnectionService_method_names[] = {
  "/sro.gamebackend.ConnectionService/ConnectGameServer",
};

std::unique_ptr< ConnectionService::Stub> ConnectionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ConnectionService::Stub> stub(new ConnectionService::Stub(channel, options));
  return stub;
}

ConnectionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ConnectGameServer_(ConnectionService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ConnectionService::Stub::ConnectGameServer(::grpc::ClientContext* context, const ::sro::gamebackend::ConnectGameServerRequest& request, ::sro::gamebackend::ConnectGameServerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::sro::gamebackend::ConnectGameServerRequest, ::sro::gamebackend::ConnectGameServerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ConnectGameServer_, context, request, response);
}

void ConnectionService::Stub::async::ConnectGameServer(::grpc::ClientContext* context, const ::sro::gamebackend::ConnectGameServerRequest* request, ::sro::gamebackend::ConnectGameServerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::sro::gamebackend::ConnectGameServerRequest, ::sro::gamebackend::ConnectGameServerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectGameServer_, context, request, response, std::move(f));
}

void ConnectionService::Stub::async::ConnectGameServer(::grpc::ClientContext* context, const ::sro::gamebackend::ConnectGameServerRequest* request, ::sro::gamebackend::ConnectGameServerResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ConnectGameServer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>* ConnectionService::Stub::PrepareAsyncConnectGameServerRaw(::grpc::ClientContext* context, const ::sro::gamebackend::ConnectGameServerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::sro::gamebackend::ConnectGameServerResponse, ::sro::gamebackend::ConnectGameServerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ConnectGameServer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::sro::gamebackend::ConnectGameServerResponse>* ConnectionService::Stub::AsyncConnectGameServerRaw(::grpc::ClientContext* context, const ::sro::gamebackend::ConnectGameServerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncConnectGameServerRaw(context, request, cq);
  result->StartCall();
  return result;
}

ConnectionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ConnectionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ConnectionService::Service, ::sro::gamebackend::ConnectGameServerRequest, ::sro::gamebackend::ConnectGameServerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ConnectionService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::sro::gamebackend::ConnectGameServerRequest* req,
             ::sro::gamebackend::ConnectGameServerResponse* resp) {
               return service->ConnectGameServer(ctx, req, resp);
             }, this)));
}

ConnectionService::Service::~Service() {
}

::grpc::Status ConnectionService::Service::ConnectGameServer(::grpc::ServerContext* context, const ::sro::gamebackend::ConnectGameServerRequest* request, ::sro::gamebackend::ConnectGameServerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sro
}  // namespace gamebackend

