//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcClient.h"
#include "SSroChat/ChatMessage.h"
#include "ChatClient.generated.h"

DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceConnectChannelResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroChatChatMessage&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceConnectDirectMessageResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroChatChatMessage&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceSendChatMessageResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceSendDirectMessageResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceGetChannelResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroChatChatChannel&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceAllChatChannelsResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroChatChatChannels&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceCreateChannelResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceDeleteChannelResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceEditChannelResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceGetAuthorizedChatChannelsResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcSroChatChatChannels&, Response);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams(FOnChatServiceUpdateUserChatChannelAuthorizationsResponse, FGrpcContextHandle, Handle, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UChatServiceClient : public UGrpcClient
{
	GENERATED_BODY()

public:
	UPROPERTY(BlueprintAssignable)
	FOnChatServiceConnectChannelResponse OnConnectChannelResponse;

	UPROPERTY(BlueprintAssignable)
	FOnChatServiceConnectDirectMessageResponse OnConnectDirectMessageResponse;

	UPROPERTY(BlueprintAssignable)
	FOnChatServiceSendChatMessageResponse OnSendChatMessageResponse;

	UPROPERTY(BlueprintAssignable)
	FOnChatServiceSendDirectMessageResponse OnSendDirectMessageResponse;

	UPROPERTY(BlueprintAssignable)
	FOnChatServiceGetChannelResponse OnGetChannelResponse;

	UPROPERTY(BlueprintAssignable)
	FOnChatServiceAllChatChannelsResponse OnAllChatChannelsResponse;

	UPROPERTY(BlueprintAssignable)
	FOnChatServiceCreateChannelResponse OnCreateChannelResponse;

	UPROPERTY(BlueprintAssignable)
	FOnChatServiceDeleteChannelResponse OnDeleteChannelResponse;

	UPROPERTY(BlueprintAssignable)
	FOnChatServiceEditChannelResponse OnEditChannelResponse;

	UPROPERTY(BlueprintAssignable)
	FOnChatServiceGetAuthorizedChatChannelsResponse OnGetAuthorizedChatChannelsResponse;

	UPROPERTY(BlueprintAssignable)
	FOnChatServiceUpdateUserChatChannelAuthorizationsResponse OnUpdateUserChatChannelAuthorizationsResponse;

public:
	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitConnectChannel();

	UFUNCTION(BlueprintCallable)
	void ConnectChannel(FGrpcContextHandle Handle, const FGrpcSroChatChatChannelTarget& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitConnectDirectMessage();

	UFUNCTION(BlueprintCallable)
	void ConnectDirectMessage(FGrpcContextHandle Handle, const FGrpcSroCharactersCharacterTarget& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitSendChatMessage();

	UFUNCTION(BlueprintCallable)
	void SendChatMessage(FGrpcContextHandle Handle, const FGrpcSroChatSendChatMessageRequest& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitSendDirectMessage();

	UFUNCTION(BlueprintCallable)
	void SendDirectMessage(FGrpcContextHandle Handle, const FGrpcSroChatSendDirectMessageRequest& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitGetChannel();

	UFUNCTION(BlueprintCallable)
	void GetChannel(FGrpcContextHandle Handle, const FGrpcSroChatChatChannelTarget& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitAllChatChannels();

	UFUNCTION(BlueprintCallable)
	void AllChatChannels(FGrpcContextHandle Handle, const FGrpcGoogleProtobufEmpty& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitCreateChannel();

	UFUNCTION(BlueprintCallable)
	void CreateChannel(FGrpcContextHandle Handle, const FGrpcSroChatCreateChannelMessage& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitDeleteChannel();

	UFUNCTION(BlueprintCallable)
	void DeleteChannel(FGrpcContextHandle Handle, const FGrpcSroChatChatChannelTarget& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitEditChannel();

	UFUNCTION(BlueprintCallable)
	void EditChannel(FGrpcContextHandle Handle, const FGrpcSroChatUpdateChatChannelRequest& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitGetAuthorizedChatChannels();

	UFUNCTION(BlueprintCallable)
	void GetAuthorizedChatChannels(FGrpcContextHandle Handle, const FGrpcSroCharactersCharacterTarget& Request);

	UFUNCTION(BlueprintCallable)
	FGrpcContextHandle InitUpdateUserChatChannelAuthorizations();

	UFUNCTION(BlueprintCallable)
	void UpdateUserChatChannelAuthorizations(FGrpcContextHandle Handle, const FGrpcSroChatRequestChatChannelAuthChange& Request);

public:
	virtual void Shutdown() override;

	UFUNCTION(BlueprintCallable)
	void TryCancel(FGrpcContextHandle Handle);
};

