//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "CoreMinimal.h"
#include "Kismet/BlueprintAsyncActionBase.h"
#include "TurboLinkGrpcClient.h"
#include "ChatMessage.h"
#include "ChatNode.generated.h"

class UChatService;
class UChatServiceClient;

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallChatServiceSendChatMessage : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FChatServiceSendChatMessageDelegate, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ChatService SendChatMessage"), Category = "TurboLink|ChatService")
	static UCallChatServiceSendChatMessage* SendChatMessage(UObject* WorldContextObject, const FGrpcSroChatSendChatMessageRequest& Request);

	UPROPERTY(BlueprintAssignable)
	FChatServiceSendChatMessageDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FChatServiceSendChatMessageDelegate OnFail;

private:
	UPROPERTY()
	UChatService* ChatService;
	
	UPROPERTY()
	UChatServiceClient* ChatServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroChatSendChatMessageRequest Request;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallChatServiceSendDirectMessage : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FChatServiceSendDirectMessageDelegate, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ChatService SendDirectMessage"), Category = "TurboLink|ChatService")
	static UCallChatServiceSendDirectMessage* SendDirectMessage(UObject* WorldContextObject, const FGrpcSroChatSendDirectMessageRequest& Request);

	UPROPERTY(BlueprintAssignable)
	FChatServiceSendDirectMessageDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FChatServiceSendDirectMessageDelegate OnFail;

private:
	UPROPERTY()
	UChatService* ChatService;
	
	UPROPERTY()
	UChatServiceClient* ChatServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroChatSendDirectMessageRequest Request;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallChatServiceGetChannel : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FChatServiceGetChannelDelegate, const FGrpcResult&, GrpcResult, const FGrpcSroChatChatChannel&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ChatService GetChannel"), Category = "TurboLink|ChatService")
	static UCallChatServiceGetChannel* GetChannel(UObject* WorldContextObject, const FGrpcSroChatChatChannelTarget& Request);

	UPROPERTY(BlueprintAssignable)
	FChatServiceGetChannelDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FChatServiceGetChannelDelegate OnFail;

private:
	UPROPERTY()
	UChatService* ChatService;
	
	UPROPERTY()
	UChatServiceClient* ChatServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroChatChatChannelTarget Request;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroChatChatChannel& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallChatServiceAllChatChannels : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FChatServiceAllChatChannelsDelegate, const FGrpcResult&, GrpcResult, const FGrpcSroChatChatChannels&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ChatService AllChatChannels"), Category = "TurboLink|ChatService")
	static UCallChatServiceAllChatChannels* AllChatChannels(UObject* WorldContextObject, const FGrpcGoogleProtobufEmpty& Request);

	UPROPERTY(BlueprintAssignable)
	FChatServiceAllChatChannelsDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FChatServiceAllChatChannelsDelegate OnFail;

private:
	UPROPERTY()
	UChatService* ChatService;
	
	UPROPERTY()
	UChatServiceClient* ChatServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcGoogleProtobufEmpty Request;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroChatChatChannels& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallChatServiceCreateChannel : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FChatServiceCreateChannelDelegate, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ChatService CreateChannel"), Category = "TurboLink|ChatService")
	static UCallChatServiceCreateChannel* CreateChannel(UObject* WorldContextObject, const FGrpcSroChatCreateChannelMessage& Request);

	UPROPERTY(BlueprintAssignable)
	FChatServiceCreateChannelDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FChatServiceCreateChannelDelegate OnFail;

private:
	UPROPERTY()
	UChatService* ChatService;
	
	UPROPERTY()
	UChatServiceClient* ChatServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroChatCreateChannelMessage Request;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallChatServiceDeleteChannel : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FChatServiceDeleteChannelDelegate, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ChatService DeleteChannel"), Category = "TurboLink|ChatService")
	static UCallChatServiceDeleteChannel* DeleteChannel(UObject* WorldContextObject, const FGrpcSroChatChatChannelTarget& Request);

	UPROPERTY(BlueprintAssignable)
	FChatServiceDeleteChannelDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FChatServiceDeleteChannelDelegate OnFail;

private:
	UPROPERTY()
	UChatService* ChatService;
	
	UPROPERTY()
	UChatServiceClient* ChatServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroChatChatChannelTarget Request;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallChatServiceEditChannel : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FChatServiceEditChannelDelegate, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ChatService EditChannel"), Category = "TurboLink|ChatService")
	static UCallChatServiceEditChannel* EditChannel(UObject* WorldContextObject, const FGrpcSroChatUpdateChatChannelRequest& Request);

	UPROPERTY(BlueprintAssignable)
	FChatServiceEditChannelDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FChatServiceEditChannelDelegate OnFail;

private:
	UPROPERTY()
	UChatService* ChatService;
	
	UPROPERTY()
	UChatServiceClient* ChatServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroChatUpdateChatChannelRequest Request;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallChatServiceGetAuthorizedChatChannels : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FChatServiceGetAuthorizedChatChannelsDelegate, const FGrpcResult&, GrpcResult, const FGrpcSroChatChatChannels&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ChatService GetAuthorizedChatChannels"), Category = "TurboLink|ChatService")
	static UCallChatServiceGetAuthorizedChatChannels* GetAuthorizedChatChannels(UObject* WorldContextObject, const FGrpcSroCharactersCharacterTarget& Request);

	UPROPERTY(BlueprintAssignable)
	FChatServiceGetAuthorizedChatChannelsDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FChatServiceGetAuthorizedChatChannelsDelegate OnFail;

private:
	UPROPERTY()
	UChatService* ChatService;
	
	UPROPERTY()
	UChatServiceClient* ChatServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroCharactersCharacterTarget Request;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroChatChatChannels& Response);

	void Shutdown();
};

UCLASS(ClassGroup = TurboLink)
class TURBOLINKGRPC_API UCallChatServiceUpdateUserChatChannelAuthorizations : public UBlueprintAsyncActionBase
{
	GENERATED_BODY()

public:
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FChatServiceUpdateUserChatChannelAuthorizationsDelegate, const FGrpcResult&, GrpcResult, const FGrpcGoogleProtobufEmpty&, Response);

	UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true", WorldContext = "WorldContextObject", DisplayName = "Call ChatService UpdateUserChatChannelAuthorizations"), Category = "TurboLink|ChatService")
	static UCallChatServiceUpdateUserChatChannelAuthorizations* UpdateUserChatChannelAuthorizations(UObject* WorldContextObject, const FGrpcSroChatRequestChatChannelAuthChange& Request);

	UPROPERTY(BlueprintAssignable)
	FChatServiceUpdateUserChatChannelAuthorizationsDelegate OnSuccess;

	UPROPERTY(BlueprintAssignable)
	FChatServiceUpdateUserChatChannelAuthorizationsDelegate OnFail;

private:
	UPROPERTY()
	UChatService* ChatService;
	
	UPROPERTY()
	UChatServiceClient* ChatServiceClient;
	
	FGrpcContextHandle Context;
	FGrpcSroChatRequestChatChannelAuthChange Request;

	UFUNCTION()
	void OnServiceStateChanged(EGrpcServiceState NewState);
	
	UFUNCTION()
	void OnContextStateChange(FGrpcContextHandle Handle, EGrpcContextState State);

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcGoogleProtobufEmpty& Response);

	void Shutdown();
};
