//Generated by TurboLink CodeGenerator, do not edit!
#include "SSroChat/ChatMessage.h"

FGrpcSroChatUpdateChatChannelRequest_name UGrpcSroChatUpdateChatChannelRequest_nameHelperLibrary::Make_name(EGrpcSroChatUpdateChatChannelRequest_name _nameCase, 
    FString Name 
)
{
    FGrpcSroChatUpdateChatChannelRequest_name _name;
    _name._nameCase = _nameCase;
    _name.Name = Name;

    return _name;
}

void UGrpcSroChatUpdateChatChannelRequest_nameHelperLibrary::Break_name(const FGrpcSroChatUpdateChatChannelRequest_name& _name, EGrpcSroChatUpdateChatChannelRequest_name& _nameCase, 
    FString& Name 
)
{
    _nameCase = _name._nameCase;
    Name = _name.Name;
}

FGrpcSroChatUpdateChatChannelRequest_dimension UGrpcSroChatUpdateChatChannelRequest_dimensionHelperLibrary::Make_dimension(EGrpcSroChatUpdateChatChannelRequest_dimension _dimensionCase, 
    FString Dimension 
)
{
    FGrpcSroChatUpdateChatChannelRequest_dimension _dimension;
    _dimension._dimensionCase = _dimensionCase;
    _dimension.Dimension = Dimension;

    return _dimension;
}

void UGrpcSroChatUpdateChatChannelRequest_dimensionHelperLibrary::Break_dimension(const FGrpcSroChatUpdateChatChannelRequest_dimension& _dimension, EGrpcSroChatUpdateChatChannelRequest_dimension& _dimensionCase, 
    FString& Dimension 
)
{
    _dimensionCase = _dimension._dimensionCase;
    Dimension = _dimension.Dimension;
}

