//Generated by TurboLink CodeGenerator, do not edit!
#include "ConnectionService_Private.h"

void UConnectionServiceConnectGameServerLambdaWrapper::OnResponse(FGrpcContextHandle _Handle, const FGrpcResult& GrpcResult, const FGrpcSroGamebackendConnectGameServerResponse& Response)
{
	if (_Handle != this->Handle) return;

	Lambda(GrpcResult, Response);
	InnerClient->OnConnectGameServerResponse.RemoveDynamic(this, &UConnectionServiceConnectGameServerLambdaWrapper::OnResponse);
}

