//Generated by TurboLink CodeGenerator, do not edit!
#include "SSroGamebackend/ConnectionMessage.h"
#include "TurboLinkGrpcContext.h"
#include "sro/gamebackend/connection.pb.h"

void GRPC_TO_TURBOLINK(const ::sro::gamebackend::ConnectGameServerResponse* in, FGrpcSroGamebackendConnectGameServerResponse* out);
void TURBOLINK_TO_GRPC(const FGrpcSroGamebackendConnectGameServerResponse* in, ::sro::gamebackend::ConnectGameServerResponse* out);

typedef grpc::ClientAsyncResponseReader<::sro::gamebackend::ConnectGameServerResponse> ConnectionService_ConnectGameServer_ReaderWriter;
