//Generated by TurboLink CodeGenerator, do not edit!
#include "SSro/GlobalsMessage.h"

FGrpcSroUserTargetTarget UGrpcSroUserTargetTargetHelperLibrary::MakeTarget(EGrpcSroUserTargetTarget TargetCase, 
    FString Id, FString Username 
)
{
    FGrpcSroUserTargetTarget Target;
    Target.TargetCase = TargetCase;
    Target.Id = Id;
    Target.Username = Username;

    return Target;
}

void UGrpcSroUserTargetTargetHelperLibrary::BreakTarget(const FGrpcSroUserTargetTarget& Target, EGrpcSroUserTargetTarget& TargetCase, 
    FString& Id, FString& Username 
)
{
    TargetCase = Target.TargetCase;
    Id = Target.Id;
    Username = Target.Username;
}

