//Generated by TurboLink CodeGenerator, do not edit!
#include "SSro/HealthMessage.h"
#include "TurboLinkGrpcContext.h"
#include "health.pb.h"

void GRPC_TO_TURBOLINK(const ::sro::HealthMessage* in, FGrpcSroHealthMessage* out);
void TURBOLINK_TO_GRPC(const FGrpcSroHealthMessage* in, ::sro::HealthMessage* out);

typedef grpc::ClientAsyncResponseReader<::sro::HealthMessage> HealthService_Health_ReaderWriter;
