//Generated by TurboLink CodeGenerator, do not edit!
#pragma once

#include "SSro/HealthService.h"
#include "TurboLinkGrpcManager_Private.h"
#include "health.grpc.pb.h"
#include "HealthService_Private.generated.h"

class UHealthService::Private
{
public:
	std::shared_ptr<UTurboLinkGrpcManager::Private::ServiceChannel> Channel;
	std::unique_ptr<::sro::HealthService::Stub> Stub;
};

UCLASS()
class UHealthServiceHealthLambdaWrapper : public UObject
{
	GENERATED_BODY()
public:
	UPROPERTY()
	UHealthServiceClient* InnerClient;

	UFUNCTION()
	void OnResponse(FGrpcContextHandle Handle, const FGrpcResult& GrpcResult, const FGrpcSroHealthMessage& Response);
public:
	FGrpcContextHandle Handle;
	UHealthService::FHealthLambda Lambda;
};

