//Generated by TurboLink CodeGenerator, do not edit!
#include "WrappersMarshaling.h"

void GRPC_TO_TURBOLINK(const ::google::protobuf::DoubleValue* in, FGrpcGoogleProtobufDoubleValue* out)
{
    out->Value=in->value();
}

void TURBOLINK_TO_GRPC(const FGrpcGoogleProtobufDoubleValue* in, ::google::protobuf::DoubleValue* out)
{
    out->set_value(in->Value);
}

void GRPC_TO_TURBOLINK(const ::google::protobuf::FloatValue* in, FGrpcGoogleProtobufFloatValue* out)
{
    out->Value=in->value();
}

void TURBOLINK_TO_GRPC(const FGrpcGoogleProtobufFloatValue* in, ::google::protobuf::FloatValue* out)
{
    out->set_value(in->Value);
}

void GRPC_TO_TURBOLINK(const ::google::protobuf::Int64Value* in, FGrpcGoogleProtobufInt64Value* out)
{
    out->Value=in->value();
}

void TURBOLINK_TO_GRPC(const FGrpcGoogleProtobufInt64Value* in, ::google::protobuf::Int64Value* out)
{
    out->set_value(in->Value);
}

void GRPC_TO_TURBOLINK(const ::google::protobuf::UInt64Value* in, FGrpcGoogleProtobufUInt64Value* out)
{
    out->Value=in->value();
}

void TURBOLINK_TO_GRPC(const FGrpcGoogleProtobufUInt64Value* in, ::google::protobuf::UInt64Value* out)
{
    out->set_value(in->Value);
}

void GRPC_TO_TURBOLINK(const ::google::protobuf::Int32Value* in, FGrpcGoogleProtobufInt32Value* out)
{
    out->Value=in->value();
}

void TURBOLINK_TO_GRPC(const FGrpcGoogleProtobufInt32Value* in, ::google::protobuf::Int32Value* out)
{
    out->set_value(in->Value);
}

void GRPC_TO_TURBOLINK(const ::google::protobuf::UInt32Value* in, FGrpcGoogleProtobufUInt32Value* out)
{
    out->Value=in->value();
}

void TURBOLINK_TO_GRPC(const FGrpcGoogleProtobufUInt32Value* in, ::google::protobuf::UInt32Value* out)
{
    out->set_value(in->Value);
}

void GRPC_TO_TURBOLINK(const ::google::protobuf::BoolValue* in, FGrpcGoogleProtobufBoolValue* out)
{
    out->Value=in->value();
}

void TURBOLINK_TO_GRPC(const FGrpcGoogleProtobufBoolValue* in, ::google::protobuf::BoolValue* out)
{
    out->set_value(in->Value);
}

void GRPC_TO_TURBOLINK(const ::google::protobuf::StringValue* in, FGrpcGoogleProtobufStringValue* out)
{
    out->Value=UTF8_TO_TCHAR(in->value().c_str());
}

void TURBOLINK_TO_GRPC(const FGrpcGoogleProtobufStringValue* in, ::google::protobuf::StringValue* out)
{
    out->set_value(TCHAR_TO_UTF8(*(in->Value)));
}

void GRPC_TO_TURBOLINK(const ::google::protobuf::BytesValue* in, FGrpcGoogleProtobufBytesValue* out)
{
    out->Value=FBytes((const uint8*)in->value().c_str(), in->value().length());
}

void TURBOLINK_TO_GRPC(const FGrpcGoogleProtobufBytesValue* in, ::google::protobuf::BytesValue* out)
{
    out->set_value(std::string((const char*)(in->Value.Value.GetData()), (size_t)in->Value.Value.Num()));
}

