//Generated by TurboLink CodeGenerator, do not edit!
#pragma once
#include "TurboLinkGrpcService.h"
#include "SSroGamebackend/ConnectionClient.h"
#include "ConnectionService.generated.h"

class UTurboLinkGrpcManager;

UCLASS(ClassGroup = TurboLink, BlueprintType)
class TURBOLINKGRPC_API UConnectionService : public UGrpcService
{
	GENERATED_BODY()
public:
	UFUNCTION(BlueprintCallable)
	virtual void Connect() override;
	
	UFUNCTION(BlueprintCallable)
	virtual EGrpcServiceState GetServiceState() const override;

	UFUNCTION(BlueprintCallable)
	UConnectionServiceClient* MakeClient();

private:
	virtual void Shutdown() override;

	UPROPERTY()
	UConnectionServiceClient* InnerClient; 
public:
	typedef TFunction<void(const FGrpcResult& GrpcResult, const FGrpcSroGamebackendConnectGameServerResponse& Response)> FConnectGameServerLambda;
	void CallConnectGameServer(const FGrpcSroCharactersCharacterTarget& Request, FConnectGameServerLambda Lambda);

public:
	class Private;
	Private* const d = nullptr;

public:
	UConnectionService();
	virtual ~UConnectionService();
};

